---
driver:
  name: docker

provisioner:
  name: chef_zero
  product_name: chef
  product_version: 12.21.31

verifier:
  name: inspec

platforms:
  - name: ubuntu-16.04

suites:
  - name: default
    run_list:
      - recipe[custom_apache::default]
    attributes:
